spring:
  security:
    oauth2:
      client:
        registration:   # 클라이언트 애플리케이션(Spring Boot)에 대한 설정을 포함합니다.
          kakao:
            #앱-앱 설정-앱-플랫폼 키
            client-id: ${KAKAO_CLIENT_ID}  #d87e69bdc474e83377581de6926ecee1       # Rest Api 키
            client-secret: ${KAKAO_CLIENT_SECRET} #ZUt4MntR72dXyc3jwbTfg7ileORZufPO   # 클라이언트 시크릿
            client-authentication-method: client_secret_post  # 보안 설정
            authorization-grant-type: authorization_code      # 권한 부여
            # 카카오 로그인 완료 후 시큐리티가 정보를 가로챌 주소 (고정값 사용 권장)
            # {baseUrl} : 현재 서버가 실행 중인 프로토콜 + 호스트 + 포트를 자동으로 찾아내서 바꿔줌
            # Spring Security 기본 콜백 URL
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            client-name: Kakao  #화면표시용
          naver:
            client-id: ${NAVER_CLIENT_ID}  #lMFx1s4MlE9MHMLxSoUJ
            client-secret: ${NAVER_CLIENT_SECRET}  #XcFY_WPmqE
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Naver
        provider:    # OAuth2 인증 제공자(네이버)에 대한 설정 정보를 포함합니다.
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id # 카카오의 고유 식별값인 id를 키로 사용
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # ⭐ 네이버는 유저 정보가 response 키 안에 들어있어서 필수!
