name: CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: GitHub 리포지토리에서 최신 코드 가져오기
        uses: actions/checkout@v4

      - name: JDK 17 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: application.yml 파일 생성
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.yml

      - name: 테스트 및 빌드
        run: ./gradlew clean build -x test

      - name: AWS 인증 정보 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: AWS ECR 로그인
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker 이미지 생성
        run: docker build -t market-server:${{ github.sha }} .

      - name: Docker 이미지 태그
        run: docker tag market-server:${{ github.sha }} ${{ steps.login-ecr.outputs.registry }}/market-server:${{ github.sha }}

      - name: Docker 이미지 ECR에 push
        run: docker push ${{ steps.login-ecr.outputs.registry }}/market-server:${{ github.sha }}

      - name: EC2 접속 후 기존 컨테이너 제거 및 새 컨테이너 실행
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            VERSION=${{ github.sha }}
            docker stop market-server || true
            docker rm market-server || true
            docker pull ${{ steps.login-ecr.outputs.registry }}/market-server:$VERSION
            docker run -d --name market-server -p 8082:8080 ${{ steps.login-ecr.outputs.registry }}/market-server:$VERSION